const AWS_ACCESS_KEY_ID = "AKIATN6UZAGMMTCTQSYJ"
const AWS_SECRET_ACCESS_KEY = "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"
const AWS_S3_BUCKET_NAME = "test-bucket-106"

module.exports = {AWS_ACCESS_KEY_ID, AWS_S3_BUCKET_NAME, AWS_SECRET_ACCESS_KEY}